# Generated by Django 3.2.3 on 2021-05-20 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tsm',
            table='home_tsm',
        ),
    ]
